### ISSUE TITLE
Gerar relatórios estatísticos

### ISSUE THREAD

**Issue by allangoncalves** [Proj-Det-Soft-2018/DocManager#4]
Prover informações administrativas em relação aos processos e interessados do sistema.

**Comment by clahzita** [comment]
Query: SELECT COUNT(id), EXTRACT(year from data_entrada) as ano, EXTRACT(month from data_entrada) AS mes FROM processos GROUP BY ano, mes ORDER BY ano, mes;
OBJETIVO: Lista quantidade de quantidade de processos por mes, ano
Estrutura para armazenar em memória: Map<Integer,ArrayList> -> <ano, (mes, quantidade)>

**Comment by clahzita** [comment]
[Tutorial JavaFX 8 - Parte 6: Gráficos de Estatistica](http://code.makery.ch/library/javafx-8-tutorial/pt/part6/)
[Introdução a gráficos com JavaFX ](http://aprendendo-javafx.blogspot.com.br/2014/08/introducao-graficos-com-javafx.html)
[Introduction to JavaFX Charts](https://docs.oracle.com/javafx/2/charts/chart-overview.htm)
[Video - JavaFX CRUD MVC Parte 4 Gráfico Vendas por Mês](https://www.youtube.com/watch?v=G9TxHA_FvHA)

**Comment by clahzita** [comment]
Query: SELECT COUNT(id) AS qte, situacao FROM processos GROUP BY situacao ORDER BY situacao;
Objetivo: Listar quantidade de processos por situação.
Estrutura para armazenar em memória: Map<Integer,Integer> -> <situacao,qtde>

Query: SELECT COUNT(id) AS qte, orgao FROM processos GROUP BY orgao ORDER BY orgao;
Objetivo: Listar quantidade de processos por orgao.
Estrutura para armazenar em memória: Map<Integer,Integer> -> <orgao,qtde>

Query: SELECT COUNT(id) AS qte, assunto FROM processos GROUP BY assunto ORDER BY assunto;
Objetivo: Listar quantidade de processos por assunto.
Estrutura para armazenar em memória: Map<Integer,Integer> -> <assunto,qtde>

**Comment by clahzita** [comment]
Query: SELECT * FROM processos WHERE  data_entrada >= DATEADD(month, -12, GETDATE());
SELECT * FROM processos WHERE  data_entrada BETWEEN unix_timestamp(date_sub(Now(), INTERVAL 12 MONTH))  AND  unix_timestamp(Now());

**Comment by clahzita** [comment]
Fazer os seguintes gráficos:
- [x] quantidade de processos por situação
- [x] quantidade de quantidade de processos por mes, ano
- [x] quantidade de processos por orgao, situacao e assunto

**Comment by clahzita** [comment]
SELECT * FROM processos WHERE data_entrada BETWEEN CURDATE() - INTERVAL 1 YEAR AND CURDATE();
OBJETIVO: Seleciona os processos do ultimo ano

**Comment by clahzita** [comment]
Query: SELECT COUNT(id), EXTRACT(year from data_entrada) as ano, EXTRACT(month from data_entrada) AS mes FROM (
SELECT * FROM processos WHERE data_entrada BETWEEN CURDATE() - INTERVAL 1 YEAR AND CURDATE() ) AS processosUltimoAno
GROUP BY ano, mes ORDER BY ano, mes;
OBJETIVO: quantidade de processos no ultimo ano.
 Estrutura para armazenar em memória: Map<Integer,ArrayList> -> <ano, (mes, quantidade)>

**Comment by clahzita** [comment]
Tudo implementado e funcionando, falta ajeitar front.
