### ISSUE TITLE
Gerar PDF de documento relacionado ao processo

### ISSUE THREAD

**Issue by allangoncalves** [Proj-Det-Soft-2018/DocManager#5]
Será gerado documento de acordo com a situação do processo.

1 - CONCLUIDO - Despacho
2 - CONTATO SEM EXITO - Certidão
3 - CONVOCADO - Certidão
4 - Demais situações - Não gera documento

**Comment by hugotho** [comment]
O tipo de pdf gerado foi simplificado, mas pode ser revisado posteriormente adicionando tratamento no XSLT
